
export type DonneesForm = {
    numform: string;
    titre: string;
    region: string;
    departement: string;
    cel: string;
    nomlv: string;
    ordre: string;
    date: string;
    typerec: string;
    nomprenomrec: string;
    sexrec: string;
    datelieunaissrec: string;
    numelecteurrec: string;
    refrecep: string;
    nomprenomspererec: string;
    nomprenomsmererec: string;
    nomprenomspv: string;
    datelieunaisspv: string;
    sexpv: string;
    nomprenomsperepv: string;
    nomprenomsmerepv: string;
    numelecteurpv?: string;
    statutpv?: string;
    argumentrec: string;
    decisioncel: string;
    argumentdec: string;
    piecesjointes: string[];
  };