export type DonneesCorrection = {
  titre: string;
  cel: string;
  region?: string;
  departement?: string;
  date: string;
  ordre: string;
  numelecteurpv?: string;
  numformulaire?: string;
  nompv: string;
  prenompv: string;
  datenaisspv: string;
  lieunaisspv: string;
  typecorrection: string;
  codeactuelv?: string;
  codenouveaulv?: string;
  nomactuelv?: string;
  nomnouveaulv?: string;
  nomcorrection?: string;
  prenomcorrection?: string;
  datenaisscorrection?: string;
  lieunaisscorrection?: string;
  sexcorrection?: string;
  professioncorrection?: string;
  nomperecorrection?: string
  prenomperecorrection?: string;  
  nommerecorrection?: string;
  prenommerecorrection?: string;
}